name: manatee
region: fra
services:
  - dockerfile_path: frontend/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      branch: master
      deploy_on_push: false
      repo: cschmatzler/manatee
    name: frontend
    routes:
      - path: /
  - dockerfile_path: backend/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      branch: master
      deploy_on_push: false
      repo: cschmatzler/manatee
    name: backend
    routes:
      - path: /api
